apiVersion: v1
kind: Service
metadata:
  name: demo-microservice
  namespace: default
spec:
  selector:
    app: demo-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
